name: discover_printers
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  wifi: ^0.1.5
  ping_discover_network: ^0.2.0+1
  image: ^3.0.0
  esc_pos_printer:
    git:
      url: https://github.com/lulumeimei/esc_pos_printer.git
  intl: ^0.16.1
  qr_flutter: ^3.2.0
  path_provider: ^1.6.5
  esc_pos_utils:
    git:
      url: https://github.com/lulumeimei/esc_pos_utils.git
  # esc_pos_utils:
  # path: ../../../esc_pos_utils
  charset_converter: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/rabbit_black.jpg
